# Generated by Django 5.0.6 on 2026-06-01 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('musicbrainz_id', models.CharField(blank=True, db_index=True, default='', help_text='MusicBrainz Artist MBID', max_length=36)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'db_table': 'catalog_artist',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(default='English', max_length=50)),
                ('genre', models.CharField(db_index=True, max_length=100)),
                ('cover_key', models.CharField(blank=True, default='', help_text='Storage path for cover art image', max_length=500)),
                ('audio_key', models.CharField(blank=True, default='', help_text='Storage path for instrumental/karaoke audio', max_length=500)),
                ('vocal_ref_key', models.CharField(blank=True, default='', help_text='Storage path for reference vocal track', max_length=500)),
                ('lrc_key', models.CharField(blank=True, default='', help_text='Storage path for synced LRC lyrics file', max_length=500)),
                ('duration', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('plays', models.PositiveIntegerField(default=0)),
                ('musicbrainz_id', models.CharField(blank=True, db_index=True, default='', help_text='MusicBrainz Recording MBID', max_length=36)),
                ('license', models.CharField(blank=True, default='All Rights Reserved', help_text='License type (e.g., CC-BY, CC-BY-NC)', max_length=100)),
                ('source_url', models.URLField(blank=True, default='', help_text='Original source URL for attribution', max_length=500)),
                ('commercial_allowed', models.BooleanField(default=False, help_text='Whether commercial use of this track is permitted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='catalog.artist')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'db_table': 'catalog_song',
                'ordering': ['-plays', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SongLyricLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(help_text='Start time in seconds from song start')),
                ('end_timestamp', models.FloatField(default=0.0, help_text='End time in seconds (0 = until next line)')),
                ('text', models.CharField(max_length=500)),
                ('words', models.JSONField(blank=True, help_text='Optional word-level timing: [{"word": "Hello", "start": 1.0, "end": 1.5}, ...]', null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='catalog.song')),
            ],
            options={
                'verbose_name': 'Lyric Line',
                'verbose_name_plural': 'Lyric Lines',
                'db_table': 'catalog_songlyricline',
                'ordering': ['song', 'timestamp'],
                'indexes': [models.Index(fields=['song', 'timestamp'], name='idx_lyric_song_time')],
            },
        ),
    ]
