# Generated by Django 5.0.6 on 2026-06-01 20:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.IntegerField(help_text='Weighted overall score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pitch_score', models.IntegerField(help_text='Pitch accuracy (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('timing_score', models.IntegerField(help_text='Timing precision (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tempo_score', models.IntegerField(help_text='Tempo consistency (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('volume_score', models.IntegerField(help_text='Volume/dynamics control (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feedback', models.TextField(help_text='NLP-generated textual feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_result', to='studio.recording')),
            ],
            options={
                'verbose_name': 'Score Result',
                'verbose_name_plural': 'Score Results',
                'db_table': 'ml_scoreresult',
            },
        ),
    ]
